apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 363410228837.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 363410228837.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: a71fe5cc
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
